### ISSUE TITLE
Fix compatibility with scan plugin 3.4

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle-enterprise-conventions-plugin#11]
It seems like the package of BuildScanExtensionWithHiddenFeatures changed between the Gradle Enterprise plugin 3.3.4 and 3.4 (`com.gradle.scan.plugin.internal.api` -> `com.gradle.enterprise.gradleplugin.internal.extension`).

We should release a new version of the plugin, so it works with the Grade Enterprise plugin 3.4 as well (or only).

**Comment by guylabs** [comment]
This has been fixed in https://github.com/gradle/gradle-enterprise-conventions-plugin/commit/43e21941f7dae3ff87b47bee0f0607c995475a8d and we already released version `0.6` of the conventions plugin. I already added a comment on the referenced PR: https://github.com/gradle/gradle-enterprise-conventions-plugin/commit/43e21941f7dae3ff87b47bee0f0607c995475a8d

@wolfs can this issue then be closed?

**Comment by etiennestuder** [comment]
@guylabs so this is breaking all public instances using GE? (Spring, Jetbrains, JUnit) If so, why did we move this package?

**Comment by guylabs** [comment]
It breaks when they use the internal `BuildScanExtensionWithHiddenFeatures` class. I'm not able to give an answer to _why_ this has been moved as I wasn't part of these changes at all.

I quickly checked all Github repositories and Spring and Junit are affected by this change: https://github.com/search?q=BuildScanExtensionWithHiddenFeatures&type=Code. @marcphilipp Could you adapt this as it was fixed in 43e2194?

We can't revert that anymore for `3.4` as this has been released already. The proper solution would be to add the `publishIfAuthenticated` method on the `BuildScanExtensionWithHiddenFeatures` class to the public API.

@ldaley I'm sorry to bother you but could you elaborate more on why we required to move that package ? And if we should do something on `3.4.1` ?

@etiennestuder who is able to have a look with Spring and Jetbrains to make the above mentioned changes to their conventions plugin to not depend on the `BuildScanExtensionWithHiddenFeatures` class?

**Comment by ldaley** [comment]
It’s internal. I moved it because there was a better home for it. No one should be using it. I was not aware anyone was.

**Comment by wolfs** [comment]
The problem is fixed in version 0.6 of this plugin, closing this issue.

**Comment by etiennestuder** [comment]
> No one should be using it.

Our public instances (Spring, JUnit, Jetbrains, Gradle) should be using it, since we do not offer them an alternative currently.

Making this API public is one way to solve the situation, but instead of doing that, we should take the opportunity to clean up those numerous publish APIs which are confusing and some of them are relics of the past.

**Comment by etiennestuder** [comment]
For the record: @runningcode will provide PRs for both Spring and JUnit to upgrade to the latest plugin version and adjust their code to the moved internal class.

**Comment by runningcode** [comment]
PR for Spring conventions plugin is here: https://github.com/spring-io/gradle-enterprise-conventions/pull/18

**Comment by runningcode** [comment]
PR for junit is here: https://github.com/junit-team/junit5/pull/2418
